- README.md
- src/components/AdminMainMenu.js
TICKET: [OFS-238](https://openimis.atlassian.net/browse/OFS-238)
> OFS-238: Added contribution point to Admin Menu entry

- src/index.js
https://openimis.atlassian.net/browse/OFS-291
> OFS-291: Fix incorrect User picker projection

- src/actions.js
- src/components/ClaimAdministratorFormPanel.js
- src/components/EnrolmentOfficerFormPanel.js
- src/components/UserForm.js
- src/components/UserMasterPanel.js
- src/reducer.js
Requires: [BE Core change ](https://github.com/openimis/openimis-be-core_py/pull/128)
TICKET: [OP-842](https://openimis.atlassian.net/browse/OP-842)
> OP-842: Adding user districts through region picker

- src/actions.js
- src/components/UserForm.js
- src/components/UserMasterPanel.js
- src/reducer.js
Part of [OP-861](https://openimis.atlassian.net/jira/software/c/projects/OTC/boards/31?selectedIssue=OP-861), 
Requires [Core change](https://github.com/openimis/openimis-be-core_py/pull/130).
> OP-861: Mandatory field handling

- src/components/UserFilter.js
While working on [OP-949](https://openimis.atlassian.net/browse/OP-949), I fixed the HF picker in `UserFilter.js`. It was always empty. I added the missing prop and it works as intended.
> hotfix/OP-949: HF select fix

- src/components/UserForm.js
[OP-1048](https://openimis.atlassian.net/browse/OP-1048)
In scope of this ticket, I removed the clearRegionDistricts action. It caused error when we try to modify the same user. After first double click, everything was working properly, but after the second one an error occured.
> OP-1048: Removal of clearRegionDistricts

- src/components/UserSearcher.js
https://openimis.atlassian.net/browse/OP-1063
This PR fixes order by email functionality when displaying list of users in admin module.
> OP-1063: fix typo in sort key

- src/components/UserMasterPanel.js
Ticket:
https://openimis.atlassian.net/browse/OP-961
Changes:
- fixed unreadable language interface in create user form by deleting doubled value
> Feature/op 961: fixed unreadable language interface in create user form

- src/components/UserSearcher.js
[OP-1068](https://openimis.atlassian.net/browse/OP-1068)
Changes:
- Enhancement of the pagination statuses and parameters in _UserForm_ (missing _last_ parameter)
[OP-1068]: https://openimis.atlassian.net/browse/OP-1068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1068: UserForm pagination fix

- src/actions.js
- src/components/EnrolmentOfficerFormPanel.js
- src/components/UserForm.js
- src/components/UserMasterPanel.js
- src/components/UserSearcher.js
- src/reducer.js
https://openimis.atlassian.net/browse/OP-1023
> OP-1023: modular IMIS:hierarchy in user's territorial rights doesn't work

- src/actions.js
- src/components/EnrolmentOfficerFormPanel.js
Ticket: https://openimis.atlassian.net/jira/software/c/projects/OTC/issues/OTC-957
Changes:
- Fixed syntax errors.
> OTC-957: Compile errors fix.

- src/components/AdminMainMenu.js
- src/components/EnrolmentVillagesPicker.js
[OTC-940](https://openimis.atlassian.net/browse/OTC-940)
Changes:
- While editing, municipalities and villages are inserted when districts change.
- Removal of unused import.
[OTC-940]: https://openimis.atlassian.net/browse/OTC-940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-940: Inserting villages fix, removal of unused import

- src/actions.js
- src/components/EnrolmentOfficerFormPanel.js
[OTC-959](https://openimis.atlassian.net/browse/OTC-959)
Changes:
- Restoring logic which was overwritten and removed by latest commit.
- Change of variable type in _action.js_.
[OTC-959]: https://openimis.atlassian.net/browse/OTC-959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-959: Unable to create/edit user fix

- src/components/UserFilter.js
- src/translations/en.json
https://openimis.atlassian.net/browse/OP-1366
This PR adds show historical data option to users.
It needs this PR: https://github.com/openimis/openimis-be-core_py/pull/168
> OP-1366: add show history filtering option

- src/actions.js
- src/components/UserFilter.js
- src/components/UserForm.js
- src/components/UserMasterPanel.js
- src/components/UserSearcher.js
- src/components/pickers/UserRolesPicker.js
- src/constants.js
- src/pages/UsersPage.js
- src/reducer.js
- src/translations/en.json
MERGING RELEASE branches
Release release/23.04
> MERGING RELEASE branches

- src/components/ClaimAdministratorFormPanel.js
- src/components/EnrolmentOfficerFormPanel.js
Ticket:
https://openimis.atlassian.net/browse/OTC-1058
Desc:
- disabled picking birth date from the future
> OTC-1058: disabled picking birth date from the future

- src/components/EnrolmentOfficerFormPanel.js
- src/components/pickers/SubstitutionEnrolmentOfficerPicker.js
- src/translations/en.json
- src/utils.js
[OP-1429](https://openimis.atlassian.net/browse/OP-1429)
Changes:
- Label and placeholder fixed.
- Fetch Substitution Officers only on dropdown click.
- New Lokalise key has been added.
[OP-1429]: https://openimis.atlassian.net/browse/OP-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1429: Label and placeholder fix, fetch SO on dropdown click

- src/components/UserFilter.js
**[BE REQUIRED](https://github.com/openimis/openimis-be-core_py/pull/182)**
[OTC-1082](https://openimis.atlassian.net/browse/OTC-1082)
Changes:
- The functionality for clearing the search criterias when clicking "Reset" button fixed.
- I got rid of useless local state as well as unnecessary functions.
[OTC-1082]: https://openimis.atlassian.net/browse/OTC-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-1082: fix resetting search criteria in user panel

- src/components/pickers/PaymentPointManagerPicker.js
- src/index.js
- src/translations/en.json
[CM-191](https://openimis.atlassian.net/browse/CM-191)
Changes:
- Payment Point Manager picker implementation.
[CM-191]: https://openimis.atlassian.net/browse/CM-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CM-191: PPM picker implementation

- src/components/UserFilter.js
https://openimis.atlassian.net/browse/OP-1445
This PR fixes querying deleted users.
It needs: https://github.com/openimis/openimis-be-core_py/pull/209
> OP-1445: change showHistory to showDeleted

- src/components/UserForm.js
[OP-1723](https://openimis.atlassian.net/browse/OP-1723)
Changes:
- Fix user form reload.
- Fix eslint errors (redundant double negations, direct mutation of state).
[OP-1723]: https://openimis.atlassian.net/browse/OP-1723?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1723: fix form reload and eslint errors

- src/components/UserFilter.js
MERGING release/23.10 into main
> MERGING release/23.10 into main

- src/components/UserFilter.js
- src/components/UserMasterPanel.js
- src/components/UserSearcher.js
- src/components/pickers/EnrolmentOfficerPicker.js
- src/components/pickers/SubstitutionEnrolmentOfficerPicker.js
- src/components/pickers/UserPicker.js
- src/constants.js
[ONI-164](https://openimis.atlassian.net/browse/ONI-164)
Changes:
- Added the 'renderLastNameFirst' setting to enable the rearrangement of field order.
[ONI-164]: https://openimis.atlassian.net/browse/ONI-164?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ONI-164: add setting to enable displaying first name before second name

- src/components/AdminMainMenu.js
[OM-131](https://openimis.atlassian.net/browse/OM-131)
Changes:
- If isWorker true, show only Users entry.
[OM-131]: https://openimis.atlassian.net/browse/OM-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OM-131: if isWorker, display users as an only entry

- src/components/AdminMainMenu.js
> hotfix: add contribution filter

- src/components/AdminMainMenu.js
[OM-131](https://openimis.atlassian.net/browse/OM-131)
https://github.com/openimis/openimis-fe-worker_voucher_js/pull/30
Changes:
- Add and use new contribution point.
[OM-131]: https://openimis.atlassian.net/browse/OM-131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OM-131: create new contribution point

- src/components/AdminMainMenu.js
MERGING develop into release/24.04
> MERGING develop into release/24.04

- src/components/UserForm.js
- src/components/UserMasterPanel.js
[OP-1771](https://openimis.atlassian.net/browse/OP-1771)
**Changes:**
After pressing reload button:
- If user updated, fetch the latest version of its data.
- If user created, fetch the created user.
[OP-1771]: https://openimis.atlassian.net/browse/OP-1771?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-1771: fix user form reload

- package.json
Added missing requirement for password validator.
> Added missing requirement
